# Type stubs for Firebase Admin SDK
# This helps VS Code resolve Firebase types

from typing import Any, Dict, List, Optional

class Client:
    def collection(self, name: str) -> Any: ...
    def document(self, path: str) -> Any: ...

class DocumentReference:
    def get(self) -> Any: ...
    def set(self, data: Dict[str, Any], merge: bool = False) -> None: ...
    def update(self, data: Dict[str, Any]) -> None: ...
    def delete(self) -> None: ...

class Query:
    def where(self, field: str, op: str, value: Any) -> 'Query': ...
    def limit(self, count: int) -> 'Query': ...
    def get(self) -> List[Any]: ...

class Collection:
    def add(self, data: Dict[str, Any]) -> tuple[Any, DocumentReference]: ...
    def document(self, doc_id: str) -> DocumentReference: ...
    def where(self, field: str, op: str, value: Any) -> Query: ...
    def limit(self, count: int) -> Query: ...
    def get(self) -> List[Any]: ...
